/** @type {import('tailwindcss').Config} */

function em(px) {
  return `${px / 16}em`
}

module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  important: true,
  theme: {
    extend: {
      colors: {
        white: 'var(--white)',
        black: 'var(--black)',
        body: 'var(--body)',
        themes: {
          light: {
            white: '#FFFFFF',
            body: '#FFFFFF',
            black: '#0F0F15',
            border: '#dde0e2',
            gray: {
              'gray-100': '#f5f6f7',
              'gray-200': '#eceff1',
              'gray-300': '#e5e8ea',
              'gray-400': '#dde0e2',
              'gray-500': '#adb5bd',
              'gray-600': '#6c757d',
              'gray-700': '#495057',
              'gray-800': '#343a40',
              'gray-900': '#212529',
            },
            primary: {
              light: '#fecb6a',
              primary: '#FCC453',
              dark: '#e0ae4b',
              fg: '#212529',
            },
            danger: {
              light: '#F9E8EA',
              danger: '#E84F61',
              dark: '#CD3D4E',
              fg: '#FFFFFF',
            },
          },
          dark: {
            white: '#0e0f10',
            body: '#0e0f10',
            black: '#f5f6f7',
            border: '#1f2224',
            gray: {
              'gray-100': '#1c1e1f',
              'gray-200': '#1b1d1f',
              'gray-300': '#27292b',
              'gray-400': '#404043',
              'gray-500': '#727374',
              'gray-600': '#9d9e9f',
              'gray-700': '#babcbd',
              'gray-800': '#d8dadb',
              'gray-900': '#F7F9FA',
            },
            primary: {
              light: '#9da2a5',
              primary: '#f5fcff',
              dark: 'white',
              fg: 'black',
            },
            danger: {
              light: '#F9E8EA',
              danger: '#fa2f43',
              dark: '#CD3D4E',
              fg: '#FFFFFF',
            },
          },
        },
        border: {
          DEFAULT: 'var(--border)',
          active: 'var(--primary)',
        },
        gray: {
          100: 'var(--gray-100)',
          200: 'var(--gray-200)',
          300: 'var(--gray-300)',
          400: 'var(--gray-400)',
          500: 'var(--gray-500)',
          600: 'var(--gray-600)',
          700: 'var(--gray-700)',
          800: 'var(--gray-800)',
          900: 'var(--gray-900)',
        },
        primary: {
          light: 'var(--primary-light)',
          DEFAULT: 'var(--primary)',
          dark: 'var(--primary-dark)',
          fg: 'var(--primary-fg)',
        },
        danger: {
          light: 'var(--danger-light)',
          DEFAULT: 'var(--danger)',
          dark: 'var(--danger-dark)',
          fg: 'var(--danger-fg)',
        },
      },
      boxShadow: {
        dropdown: '0px 4px 16px -4px rgba(97, 101, 107, 0.15)',
        offcanvas: '-24px 1px 24px -7px rgba(43, 44, 44, 0.06)',
      },
      spacing: {
        'px': em(1),
        '0.5': em(2),
        1: em(4),
        '1.5': em(6),
        '2': em(8),
        '2.5': em(10),
        '3': em(12),
        '3.5': em(14),
        '4': em(16),
        '4.5': em(18),
        '5': em(20),
        '5.5': em(22),
        '6': em(24),
        '6.5': em(26),
        '7': em(28),
        '7.5': em(30),
        '8': em(32),
        '8.5': em(34),
        '9': em(36),
        '9.5': em(38),
        '10': em(40),
        '10.5': em(44),
        D: em(44),
        xsm: em(36),
        sm: em(38),
        md: em(41),
        lg: em(48),
        xl: em(54),
        42: em(172),
      },
      minHeight: {
        D: em(44),
        xsm: em(36),
        sm: em(38),
        md: em(41),
        lg: em(48),
        xl: em(54),
      },
      minWidth: {
        D: em(44),
        xsm: em(36),
        sm: em(38),
        md: em(41),
        lg: em(48),
        xl: em(54),
      },
      maxWidth: {
        container: em(1200),
      },
      borderRadius: {
        DEFAULT: 'var(--borderRadius-default)',
        md: 'var(--borderRadius-md)',
        lg: 'var(--borderRadius-lg)',
        sm: 'var(--borderRadius-sm)',
      },
      screens: {
        xsm: '500px',
        '2xl': '1600px',
        '3xl': '1950px',
      },
      margin: {
        '7.5': '1.88rem',
      }
    },
    fontSize: {
      '-fs-5': em(12),
      '-fs-4': em(13),
      '-fs-3': em(14),
      '-fs-2': em(15),
      '-fs-1': em(16),
      DEFAULT: em(17),
      'fs-1': em(18),
      'fs-2': em(20),
      'fs-3': em(22),
      'fs-4': em(24),
      'fs-5': em(26),
      'fs-6': em(28),
      'fs-7': em(30),
      'fs-8': em(32),
      'fs-9': em(34),
      'fs-10': em(36),
      'fs-11': em(38),
      'fs-12': em(40),
      'fs-13': em(42),
      'fs-14': em(44),
      'fs-15': em(46),
      'fs-16': em(48),
      'fs-17': em(50),
      'fs-18': em(52),
      'fs-19': em(54),
      'fs-20': em(56),
      'fs-24': em(60),
      'fs-28': em(64),
      'fs-30': em(70),
    },
  },
  plugins: [],
}
